name: Cursor CLI – PR Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Cursor CLI
        run: |
          curl https://cursor.com/install -fsS | bash
          echo "$HOME/.cursor/bin" >> $GITHUB_PATH

      - name: Perform code review
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
          GH_TOKEN: ${{ github.token }}
        run: |
          cursor-agent --force --model "auto" --output-format=text --print "You are a code reviewer for Java Spring Boot. Review this PR diff and post inline comments for critical issues only.

          Context: PR ${{ github.event.pull_request.number }} in ${{ github.repository }}

          Tasks:
          1. Get PR diff: gh pr diff ${{ github.event.pull_request.number }}
          2. Review for: security bugs, performance issues, Spring Boot anti-patterns
          3. Post max 5 comments on most critical issues: gh pr review ${{ github.event.pull_request.number }} --comment

          Focus on:
          - 🔒 Security: Input validation, SQL injection
          - ⚡ Performance: N+1 queries, missing pagination  
          - ✨ Best practices: Proper exception handling, logging
          
          Keep comments short and actionable. Use emojis for severity."
