name: Cursor CLI – PR Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Cursor CLI
        run: |
          curl https://cursor.com/install -fsS | bash
          echo "$HOME/.cursor/bin" >> $GITHUB_PATH

      - name: Get PR diff
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr diff ${{ github.event.pull_request.number }} > pr_diff.txt
          echo "PR diff saved to pr_diff.txt"

      - name: Perform code review
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
          GH_TOKEN: ${{ github.token }}
        timeout-minutes: 2
        run: |
          # Use timeout and pipe to prevent hanging
          echo "Review this Java Spring Boot PR diff and post exactly 5 inline comments for the most critical issues.

          PR: ${{ github.event.pull_request.number }} in ${{ github.repository }}

          Steps:
          1. Read the diff from pr_diff.txt
          2. Identify top 5 critical issues (security, performance, Spring anti-patterns)  
          3. Post review: gh pr review ${{ github.event.pull_request.number }} --comment
          4. Print 'REVIEW_COMPLETE' and exit

          Focus: 🔒 Security bugs, ⚡ Performance issues, ✨ Spring Boot best practices
          Format: Short actionable comments with emojis" | timeout 90 cursor-agent --force --model "auto" --output-format=text || echo "Review completed or timed out"

      - name: Cleanup and confirm completion
        run: |
          rm -f pr_diff.txt
          echo "✅ Automated code review workflow completed successfully"
